name: rsa_pkcs
version: 0.1.1
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: RSA,PKCS#1,PKCS#8
homepage: https://github.com/amaurel/rsa_pkcs
dependencies:
  asn1lib: ">=0.3.0 <0.4.0"
  cipher: ">=0.7.0 <0.8.0"
dev_dependencies:
  crypto: any 
  unittest: any
