name: rsa_pkcs
version: 0.1.0
author: Alexandre Maurel <alexandre.maurel@gmail.com>
description: RSA,PKCS#1,PKCS#8
homepage: https://github.com/amaurel/rsa_pkcs
dependencies:
  asn1lib: 0.2.0
  cipher: 0.6.0
dev_dependencies:
  crypto: any 
  unittest: any
